Alle Parameter werden vorm Download ueberprueft

diff --git a/skr b/skr
--- a/skr
+++ b/skr
@@ -1,9 +1,13 @@
 #!/bin/bash
 
+allfiles(){
+echo auth-{fohls,ilpro122,ipc88,ipo51}.log{,.{1,{2..4}$1}}
+}
+
 #laedt Dateien herunter und entpackt diese ggf.
 download(){
    n=0
-   for file in auth-{fohls,ilpro122,ipc88,ipo51}.log{,.{1,{2..4}.gz}}; do
+   for file in `allfiles .gz`; do
       clear
       ((n++))
       echo Downloading file $n/20
@@ -20,6 +24,10 @@ download(){
    done
 }
 
+rmfiles(){
+rm *; cd ..; rmdir $1
+}
+
 #ein Kommandozeilenparameter
 option1(){
    #Pruefung ueber RegEx, ob es sich um eine IP-Adresse handelt
@@ -30,10 +38,10 @@ option1(){
    fi
 
    #Das erste sowie letzte Datum jeder Datei werden jeweils in einem String gespeichert 
-   mindates=$(for file in *; do
+   mindates=$(for file in `allfiles`; do
    grep -m1 "\(\(Failed password for invalid user\)\|\(Failed password for root\)\).*from $1" $file | cut -c-15
 done)
-   maxdates=$(for file in *; do
+   maxdates=$(for file in `allfiles`; do
    tac $file | grep -m1 "\(\(Failed password for invalid user\)\|\(Failed password for root\)\).*from $1" | cut -c-15
 done)
 
@@ -73,7 +81,7 @@ option2(){
    clear
    echo Analyzing log files...
 
-   #Zweiter Parameter bestimmt, welche Zeichenketten von Bedeutung sind
+   #Zweiter Parameter bestimmt, welche Zeichenketten herausgefiltert werden sollen
    case "$2" in
    "root")
       searchKey="Failed password for root"
@@ -102,6 +110,7 @@ option2(){
 ########
 #ANFANG#
 ########
+clear
 
 #prueft gueltige Kmdozeilenparameteranzahl
 if [ $# -eq 0 -o $# -gt 2 ]; then
@@ -109,6 +118,27 @@ if [ $# -eq 0 -o $# -gt 2 ]; then
    echo -e Option 1: \nFirst parameter: IP Address\n
    echo -e Option 2: \nFirst parameter: 'ipo51', 'ipc88', 'ilpro122', 'fohls' or 'all'\nSecond parameter: 'root', 'user' or 'login'\n
    exit 1
+#Ueberprufung auf gueltige IP-Adresse, falls ein Parameter uebergeben wurde
+elif [ $# -eq 1 ]; then
+   isIP=$(echo $1 | grep "\<\(\(25[0-5]\|2[0-4][0-9]\|[01]\?[0-9][0-9]\?\)\.\)\{3\}\(25[0-5]\|2[0-4][0-9]\|[01]\?[0-9][0-9]\?\)\>" | wc -l)
+   if [ $isIP -ne 1 ]; then
+      echo "Invalid IP Address"
+      exit 1
+   fi
+#Ueberpruefung auf gueltige Parameter, falls zwei eingegeben wurden
+elif [ $# -eq 2 ]; then
+   invalid=0
+   if [ "$1" != "ipo51" -a "$1" != "ipc88" -a "$1" != "ilpro122" -a "$1" != "fohls" -a "$1" != "all" ];
+then
+      echo "First parameter has to be 'ipo51', 'ipc88', 'ilpro122', 'fohls' or 'all'"
+      invalid=1
+   fi
+   if [ "$2" != "root" -a "$2" != "users" -a "$2" != "login" ]; then
+      echo "Second parameter has to be 'root', 'users' or 'login'"
+      invalid=1
+   fi
+   if [ $invalid -eq 1 ]; then exit 1; fi
+
 else   
 #Erstellen eines temporaeren Verzeichnisses
 #tempdir=$(mktemp -d logfiles.XXX)
